### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/sinatra-sessions#22]
There is a typo in the first_exercise erb file:

Your first exercise will be to set your session key-value pair.
In the route: get '/set', write a line of code that sets the :foo key of the session hash equal to 'hello'.
Then, **naviate** to the '/set' path.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
