### ISSUE TITLE
Specs vs Lab: unclearness

### ISSUE THREAD

**Issue by artross** [learn-co-curriculum/sinatra-sessions#8]
As one sees instructions, it's needed here to set :foo key of the session hash equal to 'hello'.   
```ruby
get '/first_exercise' do
  "Your first exercise will be to set your session key-value pair.\nIn the route: get '/set', write a line of code that sets the :foo key of the session hash equal to 'hello'.\nThen, naviate to the '/set' path."
end
```
Then one looks at the spec file:
```ruby
describe "GET '/set'" do
  it "sets session[:username] equal to hello" do
    get '/set'
    expect(session[:username]).to eq('Harry Potter')
  end
end
```
First, it declares that `session[:username]` should equal to 'hello', but expects it to be equal to 'Harry Potter'
Second, neither `session[:username]` nor 'Harry Potter' were mentioned in the instructions above.
Looks like something has to be changed here :)

**Comment by jmburges** [comment]
yup! Modify the reading to match the specs
